FROM maven:3.8.4-openjdk-11 AS builder
WORKDIR /app
COPY pom.xml ./
COPY src ./src
RUN mvn clean package -DskipTests
FROM openjdk:11-jre-slim
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 9090
CMD ["java", "/app/src/main/java/com.example.backend/BackendApplication.java"]