server:
  port: 9090

# \u6570\u636E\u5E93\u914D\u7F6E
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'bbcdohc'
    url: jdbc:mysql://localhost:3306/commercialComp?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true

# mybtis\u914D\u7F6E
mybatis:
  ## \u6620\u5C04xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # \u914D\u7F6E\u65E5\u5FD7
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true